Chore patches
PaccMann/paccmann_datasets pull request #102
Opened 2020-11-24 14:38 UTC by jannisborn

Minor fixes:

- #101 Pytorch import order fixed via `isort` preferences
- Added a new default SMILESLanguage dictionary (that one has seen GDSC, CCLE, BindingDB, ChEMBL (2M), VDJ and also ZINC (1.8 Billion SMILES). Should be sufficient to capture almost all tokens that can occur based on the RegExp)
- Refactored the package metadata naming to be more generic
- Some improved error handling and other housekeepping

2020-12-01 16:33 UTC, jannisborn commented
Fixing also 2 more issues:
#99 
#84

2020-12-02 12:02 UTC, C-nit requested changes
Nice work!
We need to look at the spawn thingy before merging, though.
The other suggested changes you can decide to ignore if you feel strongly about the order.

2020-12-02 12:02 UTC, C-nit commented on .travis/Dockerfile
> +RUN apt-get install python-pip curl git -y
these should happen at the top of a Dockerfile, i.e. after the FROM
I'm curious, why is it needed?

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/drug_affinity_dataset.py
> +        column_names: Tuple[str] = ['label', 'ligand_name', 'sequence_id'],
Since we are free to define the order here, I would use the "natural" one as they appear in our files. Usually a label/class column comes last, so it's not only us. This would make the test a little more readable by getting rid of `np.roll`
```suggestion
        column_names: Tuple[str] = ['ligand_name', 'sequence_id', 'label'],
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/drug_affinity_dataset.py
> +                Defaults to ['label', 'ligand_name', 'sequence_id'].
```suggestion
                Defaults to ['ligand_name', 'sequence_id', 'label'].
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/drug_affinity_dataset.py
> +        self.label_name, self.drug_name, self.protein_name = self.column_names
```suggestion
        self.drug_name, self.protein_name, self.label_name = self.column_names
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/drug_sensitivity_dataset.py
> +        column_names: Tuple[str] = ['IC50', 'drug', 'cell_line'],
```suggestion
        column_names: Tuple[str] = ['drug', 'cell_line', 'IC50'],
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/drug_sensitivity_dataset.py
> +                Defaults to ['IC50', 'drug', 'cell_line'].
```suggestion
                Defaults to ['drug', 'cell_line', 'IC50'].
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/drug_sensitivity_dataset.py
> +        self.label_name, self.drug_name, self.cell_name = self.column_names
```suggestion
        self.drug_name, self.cell_name, self.label_name = self.column_names
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/tests/test_drug_affinity_dataset.py
> +            column_names = list(np.roll(column_content.split(',')[1:], 1))
```suggestion
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/tests/test_drug_affinity_dataset.py
> +        for column_content in COLUMN_NAMES:
```suggestion
        for column_names in COLUMN_NAMES:
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/tests/test_drug_affinity_dataset.py
> +        for column_content in COLUMN_NAMES:
```suggestion
        for column_names in COLUMN_NAMES:
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/tests/test_drug_affinity_dataset.py
> +            column_names = list(np.roll(column_content.split(',')[1:], 1))
```suggestion
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/tests/test_drug_sensitivity_dataset.py
> +        for column_content in COLUMN_NAMES:
```suggestion
        for column_names in COLUMN_NAMES:
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/tests/test_drug_sensitivity_dataset.py
> +            column_names = list(np.roll(column_content.split(',')[1:], 1))
```suggestion
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/tests/test_drug_sensitivity_dataset.py
> +        for column_content in COLUMN_NAMES:
```suggestion
        for column_names in COLUMN_NAMES:
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/datasets/tests/test_drug_sensitivity_dataset.py
> +            column_names = list(np.roll(column_content.split(',')[1:], 1))
```suggestion
```

2020-12-02 12:02 UTC, C-nit commented on pytoda/smiles/tests/test_smiles_language.py
> +                pass
This Error handling does not look like we can trust the test.
I played a bit with it, and I can make the process succeed and also catch its return for assertion, but then I can't reproduce the error:

```python
from multiprocessing import Pipe
import torch


class Foo:
    def __init__(self):
        self.set_lam()

    def set_lam(self):
        self.lam = lambda x: x

    def call_lam(self):
        x = self.lam(42)
        print(x)
        return x


foo = Foo()


def worker(i, sender):
    sender.send(foo.call_lam())

if __name__ == '__main__':
    receiver, sender = Pipe(False)
    torch.multiprocessing.spawn(worker, args=(sender,))
    print(f'received {receiver.recv()}')
```
the above prints 
```console
42
received 42
```
Do you have an idea? We need to be able to make the test fail, else we can't claim to reproduce the issue.
I'll patch something similar here to see how it behaves with smiles language.

```suggestion
        from multiprocessing import Pipe
        for start_stop in [False, True]:
            s = SMILESTokenizer(add_start_and_stop=start_stop)

            def worker(i, smiles, sender):
                sender.send(s.smiles_to_token_indexes(smiles))

            receiver, sender = Pipe(False)
            torch.multiprocessing.spawn(
                s, args=('CCO', sender), nprocs=1, join=True, daemon=False, start_method='spawn'
            )
            token_indexes = receiver.recv()
            self.assertEqual(start_stop, len(token_indexes) == 3)
```

2020-12-02 12:02 UTC, C-nit commented on requirements.txt
> +coverage==5.3
`coverage` is not a requirement.
We could start a `dev_requirements.txt` or so, and also add black and flake8 to it, and also add it into the conda.yml.

2020-12-02 14:49 UTC, jannisborn commented on requirements.txt
> +coverage==5.3
I moved it away from here to the `Dockerfile`.

2020-12-09 13:14 UTC, C-nit approved these changes

2020-12-09 13:17 UTC, merged